### ISSUE TITLE
Vertical stripes pattern

### ISSUE THREAD

**Issue by ebourg** [sverx/GGTestSuite#1]
Would it be possible to display vertical stripes in addition to the horizontal and checkerboard patterns?

**Comment by sverx** [comment]
It's possible. I'll add it ASAP :smiley:

**Comment by sverx** [comment]
I hope this works fine for you: https://github.com/sverx/GGTestSuite/releases/tag/v0.14

**Comment by ebourg** [comment]
It works perfectly, thank you very much. That's perfect to check the scaling of LCD screens.

**Comment by ebourg** [comment]
And the SMS version is good too.
